export interface SslIPN {
    status: any,
    tran_date: string,
    tran_id: string,
    val_id: string,
    amount: number,
    store_amount: number,
    card_type: string,
    card_no: string,
    currency: string,
    bank_tran_id: string,
    card_issuer: string,
    card_brand: string,
    card_issuer_country: string,
    card_issuer_country_code: string,
    currency_type: string,
    currency_amount: number,
    value_a: string,
    value_b: string,
    value_c: string,
    value_d: string,
    verify_sign: string,
    verify_key: string,
    risk_level: string,
    risk_title: string
}

export enum PaymentStatus {
    "VALID" = "VALID",
    "VALIDATED" = "VALIDATED",
    "FAILED" = "FAILED",
    "CANCELLED" = "CANCELLED",
    "UNATTEMPTED" = "UNATTEMPTED",
    "EXPIRED" = "EXPIRED",
}